# Generated by Django 5.2.6 on 2025-10-26 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('informacion_proveedor', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'repuestos',
                'indexes': [models.Index(fields=['nombre'], name='repuestos_nombre_4f63b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'talleres',
                'indexes': [models.Index(fields=['region'], name='talleres_region_25ed73_idx')],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('JEFE_TALLER', 'Jefe de Taller'), ('MECANICO', 'Mecánico'), ('CHOFER', 'Chofer')], max_length=20)),
                ('hash_contrasena', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuarios',
                'indexes': [models.Index(fields=['rol'], name='usuarios_rol_936bfb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año_modelo', models.IntegerField(blank=True, null=True)),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('EN_TALLER', 'En Taller'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='OPERATIVO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conductor_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_asignados', to='app_taller.usuario')),
            ],
            options={
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='ReservaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_programada', models.DateTimeField()),
                ('fecha_fin_programada', models.DateTimeField()),
                ('proposito', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('CANCELADO', 'Cancelado'), ('COMPLETADO', 'Completado')], default='PROGRAMADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.taller')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_creadas', to='app_taller.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.vehiculo')),
            ],
            options={
                'db_table': 'reservas_vehiculos',
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ot', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta')], default='NORMAL', max_length=10)),
                ('emergencia', models.BooleanField(default=False)),
                ('descripcion_problema', models.TextField()),
                ('diagnostico_inicial', models.TextField(blank=True, null=True)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_pausa', models.DateTimeField(blank=True, null=True)),
                ('fecha_reanudacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('bloqueado_por_repuestos', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.taller')),
                ('jefe_taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_jefe_taller', to='app_taller.usuario')),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ots_asignadas', to='app_taller.usuario')),
                ('usuario_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ots_solicitadas', to='app_taller.usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.vehiculo')),
            ],
            options={
                'db_table': 'ordenes_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('nivel_minimo_stock', models.IntegerField(default=0)),
                ('nivel_maximo_stock', models.IntegerField(blank=True, null=True)),
                ('fecha_ultimo_reabastecimiento', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.repuesto')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.taller')),
            ],
            options={
                'db_table': 'inventarios',
                'indexes': [models.Index(fields=['taller'], name='inventarios_taller__b0e611_idx'), models.Index(fields=['repuesto'], name='inventarios_repuest_8ee84d_idx')],
                'unique_together': {('taller', 'repuesto')},
            },
        ),
        migrations.CreateModel(
            name='TareaOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('TERMINADA', 'Terminada')], default='PENDIENTE', max_length=20)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.ordentrabajo')),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to='app_taller.usuario')),
            ],
            options={
                'db_table': 'tareas_ot',
                'indexes': [models.Index(fields=['orden_trabajo'], name='tareas_ot_orden_t_af49be_idx'), models.Index(fields=['mecanico_asignado'], name='tareas_ot_mecanic_d5f6f7_idx'), models.Index(fields=['estado'], name='tareas_ot_estado_c864a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SolicitudRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('urgente', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=20)),
                ('numero_oc', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_proveedor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.repuesto')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.usuario')),
            ],
            options={
                'db_table': 'solicitudes_repuestos',
                'indexes': [models.Index(fields=['orden_trabajo'], name='solicitudes_orden_t_286772_idx'), models.Index(fields=['repuesto'], name='solicitudes_repuest_bec403_idx'), models.Index(fields=['estado'], name='solicitudes_estado_908e01_idx'), models.Index(fields=['numero_oc'], name='solicitudes_numero__7ffba8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo_notificacion', models.CharField(choices=[('INFO', 'Info'), ('ALERTA', 'Alerta'), ('ERROR', 'Error')], max_length=30)),
                ('tipo_entidad_relacionada', models.CharField(blank=True, max_length=20, null=True)),
                ('entidad_relacionada_id', models.IntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.usuario')),
            ],
            options={
                'db_table': 'notificaciones',
                'indexes': [models.Index(fields=['usuario'], name='notificacio_usuario_17ba4e_idx'), models.Index(fields=['leida'], name='notificacio_leida_8f2b73_idx'), models.Index(fields=['fecha_creacion'], name='notificacio_fecha_c_24f290_idx'), models.Index(fields=['tipo_notificacion'], name='notificacio_tipo_no_f028be_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_taller.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.repuesto')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.taller')),
                ('movido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.usuario')),
            ],
            options={
                'db_table': 'movimientos_repuestos',
                'indexes': [models.Index(fields=['taller'], name='movimientos_taller__373afa_idx'), models.Index(fields=['repuesto'], name='movimientos_repuest_5c6b09_idx'), models.Index(fields=['orden_trabajo'], name='movimientos_orden_t_ca6a5b_idx'), models.Index(fields=['fecha_movimiento'], name='movimientos_fecha_m_75c373_idx'), models.Index(fields=['tipo_movimiento'], name='movimientos_tipo_mo_90050f_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogEstadoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CERRADA', 'Cerrada')], max_length=20, null=True)),
                ('estado_nuevo', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PAUSADA', 'Pausada'), ('FINALIZADA', 'Finalizada'), ('CERRADA', 'Cerrada')], max_length=20)),
                ('motivo_cambio', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_taller.ordentrabajo')),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.usuario')),
            ],
            options={
                'db_table': 'log_estados_ot',
                'indexes': [models.Index(fields=['orden_trabajo'], name='log_estados_orden_t_50093a_idx'), models.Index(fields=['fecha_cambio'], name='log_estados_fecha_c_709311_idx'), models.Index(fields=['cambiado_por'], name='log_estados_cambiad_bfaf04_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('tipo_entidad', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad_id', models.IntegerField(blank=True, null=True)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('agente_usuario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_taller.usuario')),
            ],
            options={
                'db_table': 'log_auditoria',
                'indexes': [models.Index(fields=['usuario'], name='log_auditor_usuario_7aa591_idx'), models.Index(fields=['tipo_entidad'], name='log_auditor_tipo_en_523c36_idx'), models.Index(fields=['fecha_creacion'], name='log_auditor_fecha_c_5a04d1_idx'), models.Index(fields=['accion'], name='log_auditor_accion_c05f53_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntregaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('datos_firma', models.TextField(blank=True, null=True)),
                ('fecha_firma', models.DateTimeField(auto_now_add=True)),
                ('condicion_vehiculo', models.TextField(blank=True, null=True)),
                ('lectura_odometro', models.IntegerField(blank=True, null=True)),
                ('nivel_combustible', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.ordentrabajo')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_conductor', to='app_taller.usuario')),
                ('recepcionista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_recepcionista', to='app_taller.usuario')),
            ],
            options={
                'db_table': 'entregas_vehiculos',
                'indexes': [models.Index(fields=['orden_trabajo'], name='entregas_ve_orden_t_5a3f15_idx'), models.Index(fields=['conductor'], name='entregas_ve_conduct_6dff50_idx'), models.Index(fields=['recepcionista'], name='entregas_ve_recepci_d8bde2_idx'), models.Index(fields=['direccion'], name='entregas_ve_direcci_5bd6f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_ubicacion', models.TextField()),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('eta_minutos', models.IntegerField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('diagnostico_inicial', models.TextField(blank=True, null=True)),
                ('nivel_emergencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergencia_detalle', related_query_name='emergencia_detalle', to='app_taller.ordentrabajo')),
                ('mecanico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergencias_asignadas', to='app_taller.usuario')),
            ],
            options={
                'db_table': 'emergencias',
                'indexes': [models.Index(fields=['mecanico_asignado'], name='emergencias_mecanic_451af3_idx'), models.Index(fields=['nivel_emergencia'], name='emergencias_nivel_e_9837a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_entidad', models.CharField(max_length=20)),
                ('entidad_id', models.IntegerField()),
                ('tipo_archivo', models.CharField(choices=[('IMG', 'Imagen'), ('PDF', 'PDF'), ('DOC', 'Documento'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('tamaño_archivo', models.IntegerField(blank=True, null=True)),
                ('tipo_mime', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.usuario')),
            ],
            options={
                'db_table': 'archivos_adjuntos',
                'indexes': [models.Index(fields=['tipo_entidad', 'entidad_id'], name='archivos_ad_tipo_en_1cbfdc_idx'), models.Index(fields=['tipo_archivo'], name='archivos_ad_tipo_ar_848e6c_idx'), models.Index(fields=['subido_por'], name='archivos_ad_subido__6884aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['conductor_actual'], name='vehiculos_conduct_4fdd9f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['estado'], name='vehiculos_estado_bf04b7_idx'),
        ),
        migrations.AddIndex(
            model_name='reservavehiculo',
            index=models.Index(fields=['vehiculo'], name='reservas_ve_vehicul_0f7152_idx'),
        ),
        migrations.AddIndex(
            model_name='reservavehiculo',
            index=models.Index(fields=['taller'], name='reservas_ve_taller__51443e_idx'),
        ),
        migrations.AddIndex(
            model_name='reservavehiculo',
            index=models.Index(fields=['fecha_inicio_programada', 'fecha_fin_programada'], name='reservas_ve_fecha_i_744023_idx'),
        ),
        migrations.AddIndex(
            model_name='reservavehiculo',
            index=models.Index(fields=['creado_por'], name='reservas_ve_creado__e53b87_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['vehiculo'], name='ordenes_tra_vehicul_43341c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['taller'], name='ordenes_tra_taller__72c1df_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['estado'], name='ordenes_tra_estado_9aace9_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['mecanico_asignado'], name='ordenes_tra_mecanic_457da9_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['fecha_apertura', 'fecha_cierre'], name='ordenes_tra_fecha_a_0630a6_idx'),
        ),
        migrations.AddIndex(
            model_name='ordentrabajo',
            index=models.Index(fields=['emergencia'], name='ordenes_tra_emergen_6e85f1_idx'),
        ),
    ]
