# Generated by Django 5.2.7 on 2025-11-11 03:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='SolicitudRepuestoOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(blank=True, max_length=120)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='SOLICITADO', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_repuesto', to='app_taller.ordentrabajo')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_taller.repuesto')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_hechas', to='app_taller.usuario')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
