# Generated by Django 5.2.7 on 2025-11-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0002_alter_usuario_options_solicitudrepuestoot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='total_repuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='NORMAL', max_length=10),
        ),
        migrations.DeleteModel(
            name='SolicitudRepuestoOT',
        ),
    ]
