# Generated by Django 5.2.6 on 2025-11-13 03:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0003_ordentrabajo_total_repuestos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='total_mano_obra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='total_ot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
    ]
