# Generated by Django 5.2.7 on 2025-11-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0004_ordentrabajo_total_mano_obra_ordentrabajo_total_ot'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE usuarios
                ADD COLUMN requiere_cambio_clave BOOLEAN NOT NULL DEFAULT 0;
            """,
            reverse_sql="""
                -- SQLite no soporta DROP COLUMN fácilmente, lo dejamos como NOOP
                SELECT 1;
            """,
        ),
    ]