# Generated by Django 5.2.7 on 2025-11-15 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0005_fix_requiere_cambio_clave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
