# Generated by Django 5.2.6 on 2025-11-17 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0007_usuario_taller_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientorepuesto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_asignados', to='app_taller.usuario'),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientorepuesto',
            name='movido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_realizados', to='app_taller.usuario'),
        ),
    ]
