# Generated by Django 5.2.6 on 2025-11-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0009_categoriarepuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repuestos', to='app_taller.categoriarepuesto'),
        ),
    ]
