# Generated by Django 5.2.7 on 2025-11-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0010_alter_repuesto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
