# Generated by Django 5.2.7 on 2025-11-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_taller', '0011_alter_repuesto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('JEFE_TALLER', 'Jefe de Taller'), ('MECANICO', 'Mecánico'), ('CHOFER', 'Chofer'), ('RECEPCIONISTA', 'Recepcionista')], max_length=20),
        ),
    ]
