"""
Django settings for pepsico project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],   # <- añade esto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c*8#zl*5v)@j6(7@@q0+%^u34rm0%u1rdkzkw@$ep1c8-nn#lx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'app_taller',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pepsico.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pepsico.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from pathlib import Path
BASE_DIR = Path(__file__).resolve().parent.parent

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#import os
#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.postgresql",
#        "NAME": os.getenv("DB_NAME"),
#        "USER": os.getenv("DB_USER"),
#        "PASSWORD": os.getenv("DB_PASSWORD"),
#        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
#        "PORT": os.getenv("DB_PORT", "3312"),
#    }
#}


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'app_taller.backends.UsuarioBackend',
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'






# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'







import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# Archivos estáticos (CSS, JS, imágenes)
STATIC_URL = '/static/'

# Donde Django buscará archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "app_taller" / "static",
]

# (opcional para producción)
STATIC_ROOT = BASE_DIR / "staticfiles"



LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "app_taller" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

APPEND_SLASH = True


LANGUAGE_CODE = 'es-cl'
TIME_ZONE = 'America/Santiago'
USE_I18N = True
USE_TZ = True




from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'secondary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# Archivos de usuario
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"



import os

# --- Inventario API ---
INV_API_BASE   = os.getenv("INV_API_BASE",   "https://inventario.example.com/api")
INV_API_TOKEN  = os.getenv("INV_API_TOKEN",  "dev-token")
INV_API_MODE   = os.getenv("INV_API_MODE",   "MOCK")  # MOCK | REAL | OFF
INV_API_TIMEOUT = int(os.getenv("INV_API_TIMEOUT", "5"))
INV_API_RETRIES = int(os.getenv("INV_API_RETRIES", "2"))

# --- Notificaciones API ---
NOTIFY_API_BASE = os.getenv("NOTIFY_API_BASE", "https://notify.example.com/api")
NOTIFY_API_TOKEN = os.getenv("NOTIFY_API_TOKEN", "dev-token")
NOTIFY_API_MODE  = os.getenv("NOTIFY_API_MODE",  "MOCK")  # MOCK | REAL | OFF
